# Kubernetes Cluster Configurations for Multi-Cloud Platforms
# This file contains predefined configurations for different cluster types

# Azure Kubernetes Service (AKS) Configurations
aks:
  development:
    node_count: 2
    node_size: Standard_DS2_v2
    region: eastus
    enable_monitoring: true
    enable_auto_scaling: true
    min_nodes: 1
    max_nodes: 5
    
  staging:
    node_count: 3
    node_size: Standard_DS3_v2
    region: eastus
    enable_monitoring: true
    enable_auto_scaling: true
    min_nodes: 2
    max_nodes: 8
    
  production:
    node_count: 5
    node_size: Standard_DS4_v2
    region: eastus
    enable_monitoring: true
    enable_auto_scaling: true
    min_nodes: 3
    max_nodes: 15
    enable_azure_policy: true

# Amazon Elastic Kubernetes Service (EKS) Configurations
eks:
  development:
    node_count: 2
    node_type: m5.large
    region: us-east-1
    enable_auto_scaling: true
    min_nodes: 1
    max_nodes: 5
    enable_fargate: false
    
  staging:
    node_count: 3
    node_type: m5.xlarge
    region: us-east-1
    enable_auto_scaling: true
    min_nodes: 2
    max_nodes: 8
    enable_fargate: false
    
  production:
    node_count: 5
    node_type: m5.2xlarge
    region: us-east-1
    enable_auto_scaling: true
    min_nodes: 3
    max_nodes: 15
    enable_fargate: false
    enable_aws_load_balancer_controller: true

# Google Kubernetes Engine (GKE) Configurations
gke:
  development:
    node_count: 2
    machine_type: e2-standard-2
    region: us-east1
    enable_auto_scaling: true
    min_nodes: 1
    max_nodes: 5
    enable_autorepair: true
    enable_autoupgrade: true
    
  staging:
    node_count: 3
    machine_type: e2-standard-4
    region: us-east1
    enable_auto_scaling: true
    min_nodes: 2
    max_nodes: 8
    enable_autorepair: true
    enable_autoupgrade: true
    
  production:
    node_count: 5
    machine_type: e2-standard-8
    region: us-east1
    enable_auto_scaling: true
    min_nodes: 3
    max_nodes: 15
    enable_autorepair: true
    enable_autoupgrade: true
    enable_workload_identity: true
    enable_network_policy: true

# Azure Red Hat OpenShift (ARO) Configurations
aro:
  development:
    worker_count: 2
    master_vm_size: Standard_D8s_v3
    worker_vm_size: Standard_D4s_v3
    region: eastus
    api_server_visibility: Public
    ingress_visibility: Public
    enable_auto_scaling: false
    min_workers: 1
    max_workers: 5
    
  staging:
    worker_count: 3
    master_vm_size: Standard_D8s_v3
    worker_vm_size: Standard_D8s_v3
    region: eastus
    api_server_visibility: Public
    ingress_visibility: Public
    enable_auto_scaling: true
    min_workers: 2
    max_workers: 8
    
  production:
    worker_count: 5
    master_vm_size: Standard_D16s_v3
    worker_vm_size: Standard_D16s_v3
    region: eastus
    api_server_visibility: Public
    ingress_visibility: Public
    enable_auto_scaling: true
    min_workers: 3
    max_workers: 15
    enable_encryption_at_host: true

# Common configurations across all platforms
common:
  kubernetes_version: "1.28"
  enable_metrics_server: true
  enable_dashboard: false
  enable_ingress: true
  enable_cert_manager: true 