# Kubernetes Cluster Configurations for Multi-Cloud Platforms
# This file contains predefined configurations for different cluster types

# Azure Kubernetes Service (AKS) Configurations
aks:
  development:
    node_count: 2
    node_size: Standard_DS2_v2
    region: eastus
    enable_monitoring: true
    enable_auto_scaling: true
    min_nodes: 1
    max_nodes: 5
    
  staging:
    node_count: 3
    node_size: Standard_DS3_v2
    region: eastus
    enable_monitoring: true
    enable_auto_scaling: true
    min_nodes: 2
    max_nodes: 8
    
  production:
    node_count: 5
    node_size: Standard_DS4_v2
    region: eastus
    enable_monitoring: true
    enable_auto_scaling: true
    min_nodes: 3
    max_nodes: 15
    enable_azure_policy: true

# Amazon Elastic Kubernetes Service (EKS) Configurations
eks:
  development:
    node_count: 2
    node_type: m5.large
    region: us-east-1
    enable_auto_scaling: true
    min_nodes: 1
    max_nodes: 5
    enable_fargate: false
    
  staging:
    node_count: 3
    node_type: m5.xlarge
    region: us-east-1
    enable_auto_scaling: true
    min_nodes: 2
    max_nodes: 8
    enable_fargate: false
    
  production:
    node_count: 5
    node_type: m5.2xlarge
    region: us-east-1
    enable_auto_scaling: true
    min_nodes: 3
    max_nodes: 15
    enable_fargate: false
    enable_aws_load_balancer_controller: true

# Google Kubernetes Engine (GKE) Configurations
gke:
  development:
    node_count: 2
    machine_type: e2-standard-2
    region: us-east1
    enable_auto_scaling: true
    min_nodes: 1
    max_nodes: 5
    enable_autorepair: true
    enable_autoupgrade: true
    
  staging:
    node_count: 3
    machine_type: e2-standard-4
    region: us-east1
    enable_auto_scaling: true
    min_nodes: 2
    max_nodes: 8
    enable_autorepair: true
    enable_autoupgrade: true
    
  production:
    node_count: 5
    machine_type: e2-standard-8
    region: us-east1
    enable_auto_scaling: true
    min_nodes: 3
    max_nodes: 15
    enable_autorepair: true
    enable_autoupgrade: true
    enable_workload_identity: true
    enable_network_policy: true

# On-Premises OpenShift Configurations
openshift:
  development:
    project_name: "dev-multicloud"
    deployment_replicas: 2
    resource_limits:
      cpu: "500m"
      memory: "512Mi"
    resource_requests:
      cpu: "250m"
      memory: "256Mi"
    enable_auto_scaling: false
    min_replicas: 1
    max_replicas: 5
    route_enabled: true
    service_type: ClusterIP
    
  staging:
    project_name: "staging-multicloud"
    deployment_replicas: 3
    resource_limits:
      cpu: "1000m"
      memory: "1Gi"
    resource_requests:
      cpu: "500m"
      memory: "512Mi"
    enable_auto_scaling: true
    min_replicas: 2
    max_replicas: 8
    route_enabled: true
    service_type: ClusterIP
    enable_monitoring: true
    
  production:
    project_name: "prod-multicloud"
    deployment_replicas: 5
    resource_limits:
      cpu: "2000m"
      memory: "2Gi"
    resource_requests:
      cpu: "1000m"
      memory: "1Gi"
    enable_auto_scaling: true
    min_replicas: 3
    max_replicas: 15
    route_enabled: true
    service_type: LoadBalancer
    enable_monitoring: true
    enable_security_context: true
    enable_network_policy: true

# Common configurations across all platforms
common:
  kubernetes_version: "1.28"
  enable_metrics_server: true
  enable_dashboard: false
  enable_ingress: true
  enable_cert_manager: true 